### ISSUE TITLE
Some demo scripts fail

### ISSUE THREAD

**Issue by stephenfmann** [markblokpoel/mathlib#16]
Some of the demo scripts are out of sync with release 0.9.0 and even 0.9.1, so for example `Coherence.scala` fails because `value preferentialAttachment is not a member of object mathlib.graph.WUnDiGraph`. An example of a demo script that works is `VertexCover.scala`.

Part of review https://github.com/openjournals/joss-reviews/issues/6049#issuecomment-2096068069

**Comment by markblokpoel** [comment]
You are right that `Coherence.scala` demo uses a function that is currently only in beta version 0.9.2-b1. If you followed the installation instructions from the website, you probably used releases 0.9.0 or 0.9.1. These versions do not contain `preferentialAttachement` and `Coherence.scala` will subsequently not compile.

I will update the demo to use an older random graph generation function so it will compile under 0.9.1. This way the review process can move more efficiently. I'm aiming to release a new version 0.9.2 in the near future which will support more random graph algorithms. 

A note on backwards compatibility, I've revised that statement in an [earlier revision](https://github.com/openjournals/joss-reviews/issues/6049#issuecomment-2004659999). The idea is that code written in an earlier version can either be run using that older version (as you've tried), but newer code cannot be run with an older version of the library (this is the error you've encountered). I hope this clarifies things.

**Comment by markblokpoel** [comment]
I've updated the demo, can you confirm that it runs with your setup? Thanks!

**Comment by stephenfmann** [comment]
`Coherence.scala` is working; the others are all working except `GraphsDemo.scala` which throws the following on line 84:

```
value degreeOf is not a member of mathlib.graph.DiGraph[String]
    println(cycleCheck.degreeOf(N("a")))
```

This is for version `0.9.1`.

**Comment by markblokpoel** [comment]
Thanks. I've realized that the `degreeOf` and `preferentialAttachement` functions are part of the 0.9.2-b1 release. I've removed these functions from `GraphsDemo.scala` until the release of 0.9.2 as I don't want to push for a hasty release of these new functions.
