### ISSUE TITLE
Error with `tutorial/02.02-set_theory-advanced_set_theory.ipynb`

### ISSUE THREAD

**Issue by stephenfmann** [markblokpoel/mathlib#17]
I managed to install Jupyter Lab notebooks as documented in the [examples repository](https://github.com/markblokpoel/mathlib-examples). Most of the examples that have been written run as expected. However, attempting to run the second cell of `tutorial/02.02-set_theory-advanced_set_theory.ipynb`:
```
import $ivy.`com.github.markblokpoel.mathlib::mathlib:-SNAPSHOT
```
produces the following error:
```
Failed to resolve ivy dependencies:Error downloading com.github.markblokpoel.mathlib:mathlib_2.13:-SNAPSHOT
not found: ~\.ivy2\local\com.github.markblokpoel.mathlib\mathlib_2.13\-SNAPSHOT\ivys\ivy.xml
not found: https://repo1.maven.org/maven2/com/github/markblokpoel/mathlib/mathlib_2.13/-SNAPSHOT/mathlib_2.13--SNAPSHOT.pom
not found: https://jitpack.io/com/github/markblokpoel/mathlib/mathlib_2.13/-SNAPSHOT/mathlib_2.13--SNAPSHOT.pom
```

Part of https://github.com/openjournals/joss-reviews/issues/6049 (which is why I'm raising this issue here rather than in the examples repository).

**Comment by markblokpoel** [comment]
Thank you for taking a look at the notebook tutorials. This is a peculiar error message. It lists jitpack which is an old code distribution method I used during pilot versions of mathlib. It is not referenced in the most recent versions. The import statement is also different from the one used in the latest version, which is:

```
`import $ivy.`com.markblokpoel::mathlib:0.9.0`
```

Can you confirm which version of the examples you downloaded?

**Comment by stephenfmann** [comment]
Sure, I'll be able to take a look at this and https://github.com/markblokpoel/mathlib/issues/16#issuecomment-2111949780 this evening and will get back to you in both issue threads.

**Comment by stephenfmann** [comment]
The README of the [mathlib-examples](https://github.com/markblokpoel/mathlib-examples) repository contains the line: "Finally, download a copy of the repository from the releases page and unpack the files." Under **Releases** on that repository there is just one link, with link text [1 tags](https://github.com/markblokpoel/mathlib-examples/tags). That tags page has one release that leads [here](https://github.com/markblokpoel/mathlib-examples/releases/tag/v0.1.0-beta), which is what I downloaded. I would suggest changing the README and/or the list of releases.

When I download the mathlib-examples repository's main branch as a zip, the tutorial notebooks look correct ([02.02-set_theory-advanced_set_theory.ipynb](https://github.com/markblokpoel/mathlib-examples/blob/v0.1.0-beta/notebooks/tutorial/02.02-set_theory-advanced_set_theory.ipynb) does indeed contain the updated line), with the exception of [03-graph-theory.ipynb](https://github.com/markblokpoel/mathlib-examples/blob/v0.1.0-beta/notebooks/tutorial/03-graph-theory.ipynb) which appears to be empty and [04-probability-theory.ipynb](https://github.com/markblokpoel/mathlib-examples/blob/v0.1.0-beta/notebooks/tutorial/04-probability-theory.ipynb) which appears to be unfinished. I would suggest either removing them from the main branch, or creating a release that omits them.

Similarly, the `notebooks/examples` repository contains some empty notebooks which I would remove.

**Comment by markblokpoel** [comment]
thank you for the suggestions. I've updated the repository and the release file. Its much cleaner this way, and hopefully should work fully under v0.9.1.

**Comment by stephenfmann** [comment]
Looks good, happy to consider this closed.
